name: Build Compose Multiplatform App

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant Gradle permission
        run: chmod +x ./gradlew

      - name: Build common + Android + native code
        run: ./gradlew :composeApp:build

      - name: Run all tests
        run: ./gradlew :composeApp:allTests

      - name: Build iOS Framework (for Simulator)
        run: ./gradlew :composeApp:linkDebugFrameworkIosSimulatorArm64

      - name: Locate built iOS framework
        run: find . -name "*.framework" || echo "Framework not found"
